//! `aether docgen --html <out_dir>` — static HTML doc-site generator.
//!
//! Walks every `.ae` file under a project root, parses each, and writes a
//! dark-themed static site with a left-rail TOC and per-module cards for
//! every function, tool, let, and type-alias. No external CSS/JS deps;
//! everything is inlined.

use aether_ast::{Decl, Module, SourceMap};
use aether_parser::parse_module;
use aether_parser::pretty::{type_, Form};
use std::fs;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

pub fn run_docgen(project_dir: PathBuf, out_dir: PathBuf, title: Option<String>) -> ExitCode {
    if !project_dir.exists() {
        eprintln!("error: project dir {} not found", project_dir.display());
        return ExitCode::from(2);
    }
    if let Err(e) = fs::create_dir_all(&out_dir) {
        eprintln!("error: could not create {}: {e}", out_dir.display());
        return ExitCode::from(2);
    }
    let mut files: Vec<PathBuf> = Vec::new();
    collect_ae(&project_dir, &mut files);
    files.sort();
    if files.is_empty() {
        eprintln!("error: no .ae files under {}", project_dir.display());
        return ExitCode::from(1);
    }

    let title = title.unwrap_or_else(|| {
        project_dir.file_name().map_or_else(
            || "Aether docs".to_string(),
            |s| s.to_string_lossy().into_owned(),
        )
    });
    let mut sm = SourceMap::new();
    let mut modules: Vec<(PathBuf, Module)> = Vec::new();
    for path in &files {
        let Ok(src) = fs::read_to_string(path) else {
            continue;
        };
        let fid = sm.add(path.display().to_string(), src.clone());
        match parse_module(fid, &src) {
            Ok(m) => modules.push((path.clone(), m)),
            Err(e) => eprintln!("warning: skipping {} — {e}", path.display()),
        }
    }

    let html = render_site(&title, &modules, &project_dir);
    let index = out_dir.join("index.html");
    if let Err(e) = fs::write(&index, &html) {
        eprintln!("error: could not write {}: {e}", index.display());
        return ExitCode::from(1);
    }
    let css = render_css();
    let _ = fs::write(out_dir.join("style.css"), css);

    let n = modules.len();
    println!("✓ docgen → {} ({} module(s))", index.display(), n);
    ExitCode::SUCCESS
}

fn collect_ae(root: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(root) else {
        return;
    };
    for ent in entries.flatten() {
        let path = ent.path();
        // Skip dist/, target/, node_modules/.
        if path.is_dir() {
            let name = path.file_name().and_then(|s| s.to_str()).unwrap_or("");
            if matches!(name, "dist" | "target" | "node_modules" | ".aether")
                || name.starts_with('.')
            {
                continue;
            }
            collect_ae(&path, out);
        } else if path.extension().and_then(|s| s.to_str()) == Some("ae") {
            out.push(path);
        }
    }
}

fn render_site(title: &str, modules: &[(PathBuf, Module)], project_dir: &Path) -> String {
    let mut html = String::new();
    html.push_str(&format!(
        r#"<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>{title}</title>
<link rel="stylesheet" href="style.css" />
</head>
<body>
<header><h1>{title}</h1><p class="subtitle">{n} module(s) — generated by <code>aether docgen</code></p></header>
<div class="layout">
<nav class="toc">
"#,
        title = h(title),
        n = modules.len(),
    ));
    html.push_str("<ul>");
    for (path, m) in modules {
        let rel = relative_path(path, project_dir);
        let anchor = anchor_for(&rel);
        let name = display_module_name(&rel);
        html.push_str(&format!("<li><a href=\"#{anchor}\">{}</a>", h(&name)));
        if !m.decls.is_empty() {
            html.push_str("<ul class=\"sub\">");
            for d in &m.decls {
                if matches!(d, Decl::Import(_)) {
                    continue;
                }
                let id = sub_anchor(&anchor, d.name());
                html.push_str(&format!("<li><a href=\"#{id}\">{}</a></li>", h(d.name())));
            }
            html.push_str("</ul>");
        }
        html.push_str("</li>");
    }
    html.push_str("</ul></nav>\n<main>");

    for (path, m) in modules {
        let rel = relative_path(path, project_dir);
        let anchor = anchor_for(&rel);
        let name = display_module_name(&rel);
        html.push_str(&format!(
            "<section id=\"{anchor}\" class=\"module\"><h2>{} <span class=\"path\">{}</span></h2>",
            h(&name),
            h(&rel.display().to_string()),
        ));
        if let Some(doc) = &m.doc {
            html.push_str(&format!("<p class=\"mod-doc\">{}</p>", h(doc)));
        }
        for d in &m.decls {
            if matches!(d, Decl::Import(_)) {
                continue;
            }
            html.push_str(&render_decl(d, &anchor));
        }
        html.push_str("</section>\n");
    }

    html.push_str("</main></div></body></html>");
    html
}

fn render_decl(d: &Decl, mod_anchor: &str) -> String {
    let id = sub_anchor(mod_anchor, d.name());
    let mut out = String::new();
    match d {
        Decl::Fn(f) => {
            let (kw, eff) = ("fn", format_effects(&f.effects));
            let params = f
                .params
                .iter()
                .map(|p| format!("{}: {}", h(&p.name), h(&type_(&p.ty, Form::Verbose))))
                .collect::<Vec<_>>()
                .join(", ");
            let ret = type_(&f.ret, Form::Verbose);
            let sig = format!(
                "{kw} <strong>{name}</strong>({params}) -&gt; {ret}{eff}",
                name = h(&f.name),
                params = params,
                ret = h(&ret),
                eff = eff
            );
            out.push_str(&format!(
                "<article id=\"{id}\" class=\"decl fn\"><h3>{}</h3>",
                h(&f.name)
            ));
            out.push_str(&format!("<pre class=\"sig\"><code>{sig}</code></pre>"));
            if let Some(doc) = &f.doc {
                out.push_str(&format!("<p class=\"doc\">{}</p>", h(doc)));
            }
            if !f.spec.ensures.is_empty() {
                out.push_str("<p class=\"spec\"><b>ensures</b>: ");
                let parts: Vec<String> = f
                    .spec
                    .ensures
                    .iter()
                    .map(|e| h(&aether_parser::pretty::expr(e, Form::Verbose)))
                    .collect();
                out.push_str(&parts.join(" &amp;&amp; "));
                out.push_str("</p>");
            }
            out.push_str("</article>");
        }
        Decl::Let(l) => {
            let ty =
                l.ty.as_ref()
                    .map_or_else(|| "<inferred>".to_string(), |t| type_(t, Form::Verbose));
            out.push_str(&format!(
                "<article id=\"{id}\" class=\"decl let\"><h3>{}</h3>",
                h(&l.name)
            ));
            out.push_str(&format!(
                "<pre class=\"sig\"><code>let <strong>{name}</strong>: {ty}</code></pre>",
                name = h(&l.name),
                ty = h(&ty)
            ));
            if let Some(doc) = &l.doc {
                out.push_str(&format!("<p class=\"doc\">{}</p>", h(doc)));
            }
            out.push_str("</article>");
        }
        Decl::TypeAlias(t) => {
            let body = type_(&t.ty, Form::Verbose);
            out.push_str(&format!(
                "<article id=\"{id}\" class=\"decl type\"><h3>{}</h3>",
                h(&t.name)
            ));
            out.push_str(&format!(
                "<pre class=\"sig\"><code>type <strong>{name}</strong> = {body}</code></pre>",
                name = h(&t.name),
                body = h(&body)
            ));
            out.push_str("</article>");
        }
        Decl::Tool(t) => {
            let eff = format_effects(&t.effects);
            let params = t
                .params
                .iter()
                .map(|p| format!("{}: {}", h(&p.name), h(&type_(&p.ty, Form::Verbose))))
                .collect::<Vec<_>>()
                .join(", ");
            let ret = type_(&t.ret, Form::Verbose);
            out.push_str(&format!(
                "<article id=\"{id}\" class=\"decl tool\"><h3>{}</h3>",
                h(&t.name)
            ));
            out.push_str(&format!("<pre class=\"sig\"><code>tool <strong>{name}</strong>({params}) -&gt; {ret}{eff}</code></pre>",
                                  name = h(&t.name), params = params, ret = h(&ret), eff = eff));
            if let Some(doc) = &t.doc {
                out.push_str(&format!("<p class=\"doc\">{}</p>", h(doc)));
            }
            out.push_str("</article>");
        }
        Decl::Import(_) => {}
    }
    out
}

fn format_effects(e: &aether_ast::EffectRow) -> String {
    if e.is_pure() {
        return String::new();
    }
    let names: Vec<String> = e.effects.iter().map(|x| h(x.as_str())).collect();
    format!(" <span class=\"effects\">!{{{}}}</span>", names.join(", "))
}

fn relative_path(path: &Path, root: &Path) -> PathBuf {
    path.strip_prefix(root)
        .map(PathBuf::from)
        .unwrap_or_else(|_| path.to_path_buf())
}

fn anchor_for(rel: &Path) -> String {
    let s = rel.display().to_string();
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c);
        } else {
            out.push('-');
        }
    }
    out
}

fn sub_anchor(mod_anchor: &str, name: &str) -> String {
    format!("{mod_anchor}--{}", anchor_for(Path::new(name)))
}

fn display_module_name(rel: &Path) -> String {
    rel.file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("module")
        .to_string()
}

/// HTML-escape.
fn h(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            c => out.push(c),
        }
    }
    out
}

fn render_css() -> &'static str {
    r#"
:root { --bg: #0f1115; --fg: #d4d4d8; --accent: #7c3aed; --muted: #71717a; --card: #181a21; --sig: #fafafa; }
* { box-sizing: border-box; }
body { background: var(--bg); color: var(--fg); margin: 0; font: 15px/1.55 -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif; }
header { padding: 32px 48px 12px; border-bottom: 1px solid #27272a; }
header h1 { margin: 0; font-size: 30px; letter-spacing: -0.01em; }
header .subtitle { margin: 4px 0 0; color: var(--muted); }
.layout { display: grid; grid-template-columns: 280px 1fr; max-width: 1300px; margin: 0 auto; padding: 24px 32px; gap: 32px; }
.toc { position: sticky; top: 24px; align-self: start; max-height: calc(100vh - 48px); overflow-y: auto; }
.toc ul { list-style: none; padding-left: 0; margin: 0; }
.toc li { margin: 0 0 4px; }
.toc a { color: var(--fg); text-decoration: none; padding: 4px 8px; border-radius: 4px; display: block; }
.toc a:hover { background: #1f2228; color: white; }
.toc .sub { padding-left: 16px; }
.toc .sub a { font-size: 13px; color: var(--muted); }
main { min-width: 0; }
.module { padding: 24px 0; border-bottom: 1px solid #27272a; }
.module h2 { margin: 0 0 4px; font-size: 22px; }
.module .path { color: var(--muted); font-size: 13px; font-family: ui-monospace, monospace; font-weight: normal; margin-left: 8px; }
.mod-doc { color: var(--muted); margin: 8px 0 16px; }
.decl { background: var(--card); border-radius: 8px; padding: 14px 18px; margin: 12px 0; }
.decl h3 { margin: 0 0 6px; font-size: 16px; font-family: ui-monospace, monospace; }
.decl.fn h3::before   { content: "fn"   " "; color: var(--accent); }
.decl.tool h3::before { content: "tool" " "; color: #14b8a6; }
.decl.let h3::before  { content: "let"  " "; color: #f97316; }
.decl.type h3::before { content: "type" " "; color: #eab308; }
.decl .sig { background: transparent; color: var(--sig); padding: 6px 0; margin: 0; overflow-x: auto; font-family: ui-monospace, monospace; font-size: 13.5px; }
.decl .doc { color: var(--fg); margin: 8px 0 0; }
.decl .spec { color: #93c5fd; font-size: 13px; margin: 6px 0 0; font-family: ui-monospace, monospace; }
.effects { color: #14b8a6; }
"#
}

#[cfg(test)]
mod tests {
    use super::*;
    use aether_ast::FileId;

    #[test]
    fn h_escapes() {
        assert_eq!(h("<a>"), "&lt;a&gt;");
        assert_eq!(h("a & b"), "a &amp; b");
    }

    #[test]
    fn anchor_normalizes() {
        assert_eq!(anchor_for(Path::new("std/iter.ae")), "std-iter-ae");
    }

    #[test]
    fn renders_minimal_site() {
        let mut sm = SourceMap::new();
        let fid = sm.add("x.ae", "## A demo.\nfn one() -> Int effects {} { 1 }\n");
        let m = parse_module(fid, "## A demo.\nfn one() -> Int effects {} { 1 }\n").unwrap();
        let html = render_site("demo", &[(PathBuf::from("x.ae"), m)], Path::new("."));
        assert!(html.contains("<title>demo</title>"));
        assert!(html.contains("one"));
        assert!(html.contains("fn <strong>one</strong>"));
    }

    fn _unused_fid_warning_silencer() -> FileId {
        FileId(0)
    }
}
